AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket for files uploaded with Requests
Parameters:
    EnvironmentName:
        Type: String
        Description: 'e.g., qa, dev, prod (prod=www (subdomain))'
Resources:
    Sau2RequestFilesBucket:
        Type: 'AWS::S3::Bucket'
        Properties: {}

Outputs:
    Sau2RequestFilesBucket:
        Value: !Ref Sau2RequestFilesBucket
        Export:
            Name:
                !Join [':', [!Ref 'EnvironmentName', 'Sau2RequestFilesBucket']]

    Sau2RequestFilesBucketArn:
        Description: Sau2RequestFilesBucket ARN for sau environment artifact
        Value: !GetAtt Sau2RequestFilesBucket.Arn
